ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'HR';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'FieldTechnician';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'Customer';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'Vendor';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'Subcontractor';
