-- CRM core: account ownership/territory/vertical, opp forecasting + next action,
-- dated notes, follow-up tasks, leads, and an append-only customer history log.

-- AlterTable
ALTER TABLE "sales_companies" ADD COLUMN     "accountStatus" TEXT NOT NULL DEFAULT 'Prospect',
ADD COLUMN     "address" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "ownerId" TEXT,
ADD COLUMN     "ownerName" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "phone" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "territory" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "vertical" TEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE "sales_opportunities" ADD COLUMN     "forecastCategory" TEXT,
ADD COLUMN     "leadSource" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "nextStep" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "nextStepDate" TIMESTAMP(3),
ADD COLUMN     "nextStepOwnerId" TEXT,
ADD COLUMN     "nextStepOwnerName" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "probability" INTEGER,
ADD COLUMN     "stageChangedAt" TIMESTAMP(3);

-- CreateTable
CREATE TABLE "sales_notes" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "opportunityId" TEXT,
    "contactId" TEXT,
    "userId" TEXT,
    "userName" TEXT NOT NULL,
    "noteDate" TIMESTAMP(3) NOT NULL,
    "kind" TEXT NOT NULL DEFAULT 'Note',
    "body" TEXT NOT NULL DEFAULT '',
    "attachments" JSONB NOT NULL DEFAULT '[]',
    "pinned" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "sales_notes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sales_tasks" (
    "id" TEXT NOT NULL,
    "companyId" TEXT,
    "opportunityId" TEXT,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "dueDate" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'Open',
    "priority" TEXT NOT NULL DEFAULT 'Normal',
    "assigneeId" TEXT,
    "assigneeName" TEXT NOT NULL DEFAULT '',
    "createdById" TEXT,
    "createdByName" TEXT NOT NULL DEFAULT '',
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "completedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "sales_tasks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sales_leads" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "companyName" TEXT NOT NULL DEFAULT '',
    "title" TEXT NOT NULL DEFAULT '',
    "email" TEXT NOT NULL DEFAULT '',
    "phone" TEXT NOT NULL DEFAULT '',
    "source" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'New',
    "ownerId" TEXT,
    "ownerName" TEXT NOT NULL DEFAULT '',
    "territory" TEXT NOT NULL DEFAULT '',
    "vertical" TEXT NOT NULL DEFAULT '',
    "estimatedValue" INTEGER NOT NULL DEFAULT 0,
    "notes" TEXT NOT NULL DEFAULT '',
    "convertedCompanyId" TEXT,
    "convertedOpportunityId" TEXT,
    "convertedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "sales_leads_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sales_audit_logs" (
    "id" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "companyId" TEXT,
    "opportunityId" TEXT,
    "action" TEXT NOT NULL,
    "field" TEXT NOT NULL DEFAULT '',
    "oldValue" TEXT NOT NULL DEFAULT '',
    "newValue" TEXT NOT NULL DEFAULT '',
    "userId" TEXT,
    "userName" TEXT NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sales_audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "sales_notes_companyId_noteDate_idx" ON "sales_notes"("companyId", "noteDate");

-- CreateIndex
CREATE INDEX "sales_notes_opportunityId_idx" ON "sales_notes"("opportunityId");

-- CreateIndex
CREATE INDEX "sales_notes_noteDate_idx" ON "sales_notes"("noteDate");

-- CreateIndex
CREATE INDEX "sales_tasks_companyId_idx" ON "sales_tasks"("companyId");

-- CreateIndex
CREATE INDEX "sales_tasks_opportunityId_idx" ON "sales_tasks"("opportunityId");

-- CreateIndex
CREATE INDEX "sales_tasks_assigneeName_status_idx" ON "sales_tasks"("assigneeName", "status");

-- CreateIndex
CREATE INDEX "sales_tasks_dueDate_idx" ON "sales_tasks"("dueDate");

-- CreateIndex
CREATE INDEX "sales_leads_ownerName_idx" ON "sales_leads"("ownerName");

-- CreateIndex
CREATE INDEX "sales_leads_status_idx" ON "sales_leads"("status");

-- CreateIndex
CREATE INDEX "sales_audit_logs_companyId_createdAt_idx" ON "sales_audit_logs"("companyId", "createdAt");

-- CreateIndex
CREATE INDEX "sales_audit_logs_opportunityId_idx" ON "sales_audit_logs"("opportunityId");

-- CreateIndex
CREATE INDEX "sales_companies_ownerName_idx" ON "sales_companies"("ownerName");

-- AddForeignKey
ALTER TABLE "sales_notes" ADD CONSTRAINT "sales_notes_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "sales_companies"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sales_notes" ADD CONSTRAINT "sales_notes_opportunityId_fkey" FOREIGN KEY ("opportunityId") REFERENCES "sales_opportunities"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sales_notes" ADD CONSTRAINT "sales_notes_contactId_fkey" FOREIGN KEY ("contactId") REFERENCES "sales_contacts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sales_tasks" ADD CONSTRAINT "sales_tasks_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "sales_companies"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sales_tasks" ADD CONSTRAINT "sales_tasks_opportunityId_fkey" FOREIGN KEY ("opportunityId") REFERENCES "sales_opportunities"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ─── Backfill ────────────────────────────────────────────────────────────────

-- Carry existing free-text company/opportunity notes into the dated notes timeline
-- so nothing disappears from the account snapshot. Dated at the record's last update.
INSERT INTO "sales_notes" ("id", "companyId", "opportunityId", "userName", "noteDate", "kind", "body", "updatedAt")
SELECT 'legacy_c_' || c."id", c."id", NULL, 'Imported', c."updatedAt", 'Note', c."notes", CURRENT_TIMESTAMP
FROM "sales_companies" c
WHERE btrim(c."notes") <> '';

INSERT INTO "sales_notes" ("id", "companyId", "opportunityId", "userName", "noteDate", "kind", "body", "updatedAt")
SELECT 'legacy_o_' || o."id", o."companyId", o."id", COALESCE(NULLIF(o."ownerName", ''), 'Imported'), o."updatedAt", 'Note', o."notes", CURRENT_TIMESTAMP
FROM "sales_opportunities" o
WHERE btrim(o."notes") <> '';

-- Default each account's owner to the rep on its most recently updated opportunity.
UPDATE "sales_companies" c
SET "ownerName" = src."ownerName", "ownerId" = src."ownerId"
FROM (
  SELECT DISTINCT ON ("companyId") "companyId", "ownerName", "ownerId"
  FROM "sales_opportunities"
  WHERE "ownerName" <> ''
  ORDER BY "companyId", "updatedAt" DESC
) src
WHERE c."id" = src."companyId" AND c."ownerName" = '';

-- Accounts with a won deal are customers.
UPDATE "sales_companies" c
SET "accountStatus" = 'Customer'
WHERE EXISTS (
  SELECT 1 FROM "sales_opportunities" o WHERE o."companyId" = c."id" AND o."stage" = 'Closed Won'
);

-- Seed "time in stage" from the last update so aging isn't blank on day one.
UPDATE "sales_opportunities" SET "stageChangedAt" = "updatedAt" WHERE "stageChangedAt" IS NULL;
