-- AlterTable
ALTER TABLE "releases" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "rowIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "shippingType" SET DEFAULT '',
ALTER COLUMN "shipTo" SET DEFAULT '',
ALTER COLUMN "recipients" SET DEFAULT '',
ALTER COLUMN "generatedAt" DROP NOT NULL,
ALTER COLUMN "generatedBy" SET DEFAULT '',
ALTER COLUMN "rowSnapshot" SET DEFAULT '[]',
ALTER COLUMN "emailPlainText" SET DEFAULT '',
ALTER COLUMN "emailHtml" SET DEFAULT '',
ALTER COLUMN "emailSubject" SET DEFAULT '';
